# Generated by Django 4.0 on 2021-12-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('todolistapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_description',
            field=models.TextField(blank=True, default=None, max_length=3000, null=True,
                                   verbose_name='Подробное описание'),
        ),
    ]
