# Generated by Django 4.0 on 2022-01-15 07:51

from django.db import migrations


def transfer(apps, schema_editor):
    Task = apps.get_model('todolistapp.Task')

    for task in Task.objects.all():
        task.types.add(task.type.id)


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0005_task_types'),
    ]

    operations = [
        migrations.RunPython(transfer)
    ]
