# Generated by Django 4.0 on 2022-01-15 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0006_auto_20220115_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
    ]
