# Generated by Django 4.0 on 2022-01-16 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0007_remove_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='todolistapp.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='types',
            field=models.ManyToManyField(related_name='tasks', to='todolistapp.Type', verbose_name='Типы'),
        ),
    ]
