# Generated by Django 4.0 on 2022-01-18 07:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0008_alter_task_status_alter_task_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Задача'),
        ),
    ]
