# Generated by Django 4.0 on 2022-01-20 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0010_alter_task_description_alter_task_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator(message='Название задачи должно состоять исключительно из букв!', regex='^[a-zA-Zа-яА-Я ]+$')], verbose_name='Задача'),
        ),
    ]
