# Generated by Django 4.0 on 2022-01-20 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0011_alter_task_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=3000, null=True, validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Полное описание'),
        ),
    ]
