# Generated by Django 4.0 on 2022-01-29 04:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0012_alter_task_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Название проекта')),
                ('description', models.TextField(max_length=3000, validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Описание проекта')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(blank=True, default=None, null=True, verbose_name='Дата окончания')),
            ],
        ),
    ]
