# Generated by Django 4.0 on 2022-01-29 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0014_task_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelTable(
            name='project',
            table='projects',
        ),
    ]
